Added the react-hook-form with zod.
krishmarsonia/js-time pull request #2
Opened 2024-06-16 11:37 UTC by krishmarsonia

Review the changes made in the "time.tsx". Please look for performance improvement if any.

2024-06-17 15:43 UTC, vimalsonara commented
![image](https://github.com/krishmarsonia/js-time/assets/104844068/504fadc5-fd28-40eb-a1c6-4c53055ec441)

 Showing one month less than the current month in the input field.

2024-06-17 15:44 UTC, vimalsonara requested changes
![image](https://github.com/krishmarsonia/js-time/assets/104844068/77516427-8ce5-4d3b-9d48-b6aed8292511)


Showing one month less than the current month in the input field.

2024-06-17 18:14 UTC, krishmarsonia commented
I have kept the default behavior of date object, where the month in a date object is starts from 0.
![image](https://github.com/krishmarsonia/js-time/assets/69512823/a498d426-2dd9-4d8e-954b-b342f8c56be4)

2024-06-19 01:22 UTC, vimalsonara approved these changes

2024-06-19 11:53 UTC, merged